apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  ports:
    - port: 5005
      targetPort: 5005
  selector:
    app: notification-service
  type: ClusterIP
