apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  ports:
    - port: 5003
      targetPort: 5003
  selector:
    app: order-service
  type: ClusterIP
